package com.paisen.kurolauncher.helper

/**
 * Phonetic translation dictionaries and static mappings for Japanese Kana,
 * Kanji app readings, and English-Japanese application aliases.
 */
object JapaneseKanaData {

    // 2-character Kana compounds (Digraphs / Yōon & loan words)
    val KANA_COMPOUNDS: Map<String, String> = mapOf(
        // Katakana digraphs
        "キャ" to "kya", "キュ" to "kyu", "キョ" to "kyo",
        "ギャ" to "gya", "ギュ" to "gyu", "ギョ" to "gyo",
        "シャ" to "sha", "シュ" to "shu", "ショ" to "sho",
        "ジャ" to "ja",  "ジュ" to "ju",  "ジョ" to "jo",
        "チャ" to "cha", "チュ" to "chu", "チョ" to "cho",
        "ヂャ" to "ja",  "ヂュ" to "ju",  "ヂョ" to "jo",
        "ニャ" to "nya", "ニュ" to "nyu", "ニョ" to "nyo",
        "ヒャ" to "hya", "ヒュ" to "hyu", "ヒョ" to "hyo",
        "ビャ" to "bya", "ビュ" to "byu", "ビョ" to "byo",
        "ピャ" to "pya", "ピュ" to "pyu", "ピョ" to "pyo",
        "ミャ" to "mya", "ミュ" to "myu", "ミョ" to "myo",
        "リャ" to "rya", "リュ" to "ryu", "リョ" to "ryo",
        // Extended loan compounds
        "ファ" to "fa",  "フィ" to "fi",  "フェ" to "fe",  "フォ" to "fo", "フュ" to "fyu",
        "ティ" to "ti",  "ディ" to "di",  "トゥ" to "tu",  "ドゥ" to "du",
        "ウィ" to "wi",  "ウェ" to "we",  "ウォ" to "wo",
        "ヴァ" to "va",  "ヴィ" to "vi",  "ヴ"   to "vu",  "ヴェ" to "ve", "ヴォ" to "vo",
        "シェ" to "she", "ジェ" to "je",  "チェ" to "che",
        "ツァ" to "tsa", "ツィ" to "tsi", "ツェ" to "tse", "ツォ" to "tso",
        "イェ" to "ye",  "クァ" to "kwa", "クィ" to "kwi", "クェ" to "kwe", "クォ" to "kwo"
    )

    // Single Katakana character mappings
    val SINGLE_KANA: Map<Char, String> = mapOf(
        'ア' to "a", 'イ' to "i", 'ウ' to "u", 'エ' to "e", 'オ' to "o",
        'カ' to "ka", 'キ' to "ki", 'ク' to "ku", 'ケ' to "ke", 'コ' to "ko",
        'サ' to "sa", 'シ' to "shi", 'ス' to "su", 'セ' to "se", 'ソ' to "so",
        'タ' to "ta", 'チ' to "chi", 'ツ' to "tsu", 'テ' to "te", 'ト' to "to",
        'ナ' to "na", 'ニ' to "ni", 'ヌ' to "nu", 'ネ' to "ne", 'ノ' to "no",
        'ハ' to "ha", 'ヒ' to "hi", 'フ' to "fu", 'ヘ' to "he", 'ホ' to "ho",
        'マ' to "ma", 'ミ' to "mi", 'ム' to "mu", 'メ' to "me", 'モ' to "mo",
        'ヤ' to "ya", 'ユ' to "yu", 'ヨ' to "yo",
        'ラ' to "ra", 'リ' to "ri", 'ル' to "ru", 'レ' to "re", 'ロ' to "ro",
        'ワ' to "wa", 'ヲ' to "wo", 'ン' to "n",
        'ガ' to "ga", 'ギ' to "gi", 'グ' to "gu", 'ゲ' to "ge", 'ゴ' to "go",
        'ザ' to "za", 'ジ' to "ji", 'ズ' to "zu", 'ゼ' to "ze", 'ゾ' to "zo",
        'ダ' to "da", 'ヂ' to "ji", 'ヅ' to "zu", 'デ' to "de", 'ド' to "do",
        'バ' to "ba", 'ビ' to "bi", 'ブ' to "bu", 'ベ' to "be", 'ボ' to "bo",
        'パ' to "pa", 'ピ' to "pi", 'プ' to "pu", 'ペ' to "pe", 'ポ' to "po",
        'ァ' to "a", 'ィ' to "i", 'ゥ' to "u", 'ェ' to "e", 'ォ' to "o"
    )

    // Romaji to Katakana conversion entries (ordered by descending length for greedy prefix match)
    val ROMAJI_TO_KANA: List<Pair<String, String>> = listOf(
        "cch" to "ッチ", "kya" to "キャ", "kyu" to "キュ", "kyo" to "キョ",
        "gya" to "ギャ", "gyu" to "ギュ", "gyo" to "ギョ",
        "sha" to "シャ", "shu" to "シュ", "sho" to "ショ", "she" to "シェ",
        "sya" to "シャ", "syu" to "シュ", "syo" to "ショ",
        "cha" to "チャ", "chu" to "チュ", "cho" to "チョ", "che" to "チェ",
        "tya" to "チャ", "tyu" to "チュ", "tyo" to "チョ",
        "jya" to "ジャ", "jyu" to "ジュ", "jyo" to "ジョ",
        "zya" to "ジャ", "zyu" to "ジュ", "zyo" to "ジョ",
        "tsu" to "ツ", "shi" to "シ", "chi" to "チ",
        "nya" to "ニャ", "nyu" to "ニュ", "nyo" to "ニョ",
        "hya" to "ヒャ", "hyu" to "ヒュ", "hyo" to "ヒョ",
        "bya" to "ビャ", "byu" to "ビュ", "byo" to "ビョ",
        "pya" to "ピャ", "pyu" to "ピュ", "pyo" to "ピョ",
        "mya" to "ミャ", "myu" to "ミュ", "myo" to "ミョ",
        "rya" to "リャ", "ryu" to "リュ", "ryo" to "リョ",
        "tsa" to "ツァ", "tsi" to "ツィ", "tse" to "ツェ", "tso" to "ツォ",
        "fyu" to "フュ", "kwa" to "クァ", "kwi" to "クィ", "kwe" to "クェ", "kwo" to "クォ",
        "fa" to "ファ", "fi" to "フィ", "fe" to "フェ", "fo" to "フォ",
        "ti" to "ティ", "di" to "ディ", "tu" to "トゥ", "du" to "ドゥ",
        "wi" to "ウィ", "we" to "ウェ", "wo" to "ウォ",
        "va" to "ヴァ", "vi" to "ヴィ", "vu" to "ヴ", "ve" to "ヴェ", "vo" to "ヴォ",
        "ja" to "ジャ", "ji" to "ジ", "ju" to "ジュ", "je" to "ジェ", "jo" to "ジョ",
        "ka" to "カ", "ki" to "キ", "ku" to "ク", "ke" to "ケ", "ko" to "コ",
        "sa" to "サ", "si" to "シ", "su" to "ス", "se" to "セ", "so" to "ソ",
        "ta" to "タ", "te" to "テ", "to" to "ト",
        "na" to "ナ", "ni" to "ニ", "nu" to "ヌ", "ne" to "ネ", "no" to "ノ",
        "ha" to "ハ", "hi" to "ヒ", "fu" to "フ", "hu" to "フ", "he" to "ヘ", "ho" to "ホ",
        "ma" to "マ", "mi" to "ミ", "mu" to "ム", "me" to "メ", "mo" to "モ",
        "ya" to "ヤ", "yu" to "ユ", "yo" to "ヨ",
        "ra" to "ラ", "ri" to "リ", "ru" to "ル", "re" to "レ", "ro" to "ロ",
        "wa" to "ワ",
        "ga" to "ガ", "gi" to "ギ", "gu" to "グ", "ge" to "ゲ", "go" to "ゴ",
        "za" to "ザ", "zi" to "ジ", "zu" to "ズ", "ze" to "ゼ", "zo" to "ゾ",
        "da" to "ダ", "de" to "デ", "do" to "ド",
        "ba" to "バ", "bi" to "ビ", "bu" to "ブ", "be" to "ベ", "bo" to "ボ",
        "pa" to "パ", "pi" to "ピ", "pu" to "プ", "pe" to "ペ", "po" to "ポ",
        "a" to "ア", "i" to "イ", "u" to "ウ", "e" to "エ", "o" to "オ",
        "-" to "ー"
    )

    // Common Kanji app titles and compound terms mapped to their readings (Kana & Romaji)
    val KANJI_APP_READINGS: Map<String, List<String>> = mapOf(
        "設定" to listOf("せってい", "セッテイ", "settei"),
        "時計" to listOf("とけい", "トケイ", "tokei"),
        "電卓" to listOf("でんたく", "デンタク", "dentaku"),
        "電話" to listOf("でんわ", "デンワ", "denwa"),
        "連絡先" to listOf("れんらくさき", "れんらく", "レンラクサキ", "renrakusaki", "renraku"),
        "写真" to listOf("しゃしん", "シャシン", "shashin"),
        "地図" to listOf("ちず", "チズ", "chizu"),
        "天気" to listOf("てんき", "テンキ", "tenki"),
        "乗換案内" to listOf("のりかえあんない", "のりかえ", "norikaeannai", "norikae"),
        "乗り換え" to listOf("のりかえ", "norikae"),
        "乗換" to listOf("のりかえ", "norikae"),
        "録音" to listOf("ろくおん", "rokuon"),
        "音楽" to listOf("おんがく", "ongaku"),
        "動画" to listOf("どうが", "douga"),
        "読書" to listOf("どくしょ", "dokusho"),
        "辞書" to listOf("じしょ", "jisho"),
        "家計簿" to listOf("かけいぼ", "kakeibo"),
        "歩数計" to listOf("ほすうけい", "hosuukei", "hosukei"),
        "健康" to listOf("けんこう", "kenkou", "kenko"),
        "体重" to listOf("たいじゅう", "taijuu", "taiju"),
        "血圧" to listOf("けつあつ", "ketsuatsu"),
        "睡眠" to listOf("すいみん", "suimin"),
        "郵便" to listOf("ゆうびん", "yuubin", "yubin"),
        "手帳" to listOf("てちょう", "techou", "techo"),
        "買い物" to listOf("かいもの", "kaimono"),
        "通販" to listOf("つうはん", "tsuuhan", "tsuhan"),
        "銀行" to listOf("ぎんこう", "ginkou", "ginko"),
        "新聞" to listOf("しんぶん", "shinbun"),
        "将棋" to listOf("しょうぎ", "shougi", "shogi"),
        "麻雀" to listOf("まーじゃん", "majan", "mahjong"),
        "漫画" to listOf("まんが", "manga"),
        "少年" to listOf("しょうねん", "shounen", "shonen"),
        "知恵袋" to listOf("ちえぶくろ", "chiebukuro"),
        "出前" to listOf("でまえ", "demae"),
        "宅配" to listOf("たくはい", "takuhai"),
        "防災" to listOf("ぼうさい", "bousai"),
        "交通" to listOf("こうつう", "koutsuu", "kotsu"),
        "電車" to listOf("でんしゃ", "densha"),
        "駅" to listOf("えき", "eki"),
        "本" to listOf("ほん", "hon"),
        "日経" to listOf("にっけい", "nikkei"),
        "朝日" to listOf("あさひ", "asahi"),
        "読売" to listOf("よみうり", "yomiuri"),
        "毎日" to listOf("まいにち", "mainichi"),
        "産経" to listOf("さんけい", "sankei"),
        "東急" to listOf("とうきゅう", "tokyu"),
        "小田急" to listOf("おだきゅう", "odakyu"),
        "京王" to listOf("けいおう", "keio"),
        "西武" to listOf("せいぶ", "seibu"),
        "東武" to listOf("とうぶ", "tobu"),
        "京急" to listOf("けいきゅう", "keikyu"),
        "東京" to listOf("とうきょう", "tokyo"),
        "大阪" to listOf("おおさか", "osaka"),
        "京都" to listOf("きょうと", "kyoto"),
        "楽天" to listOf("らくてん", "rakuten"),
        "無印" to listOf("むじるし", "mujirushi", "muji"),
        "三井住友" to listOf("みついすみとも", "mitsuisumitomo", "smbc"),
        "三菱" to listOf("みつびし", "mitsubishi", "mufg"),
        "みずほ" to listOf("みずほ", "mizuho"),
        "ゆうちょ" to listOf("ゆうちょ", "yuucho", "yucho"),
        "検索" to listOf("けんさく", "kensaku"),
        "翻訳" to listOf("ほんやく", "honyaku"),
        "管理" to listOf("かんり", "kanri"),
        "速報" to listOf("そくほう", "sokuhou")
    )

    // Standard English and Japanese bilingual application aliases
    val BILINGUAL_APP_ALIASES: Map<String, List<String>> = mapOf(
        "設定" to listOf("settings", "setting", "config", "preferences"),
        "時計" to listOf("clock", "alarm", "timer", "stopwatch"),
        "電卓" to listOf("calculator", "calc"),
        "電話" to listOf("phone", "dialer", "call"),
        "連絡先" to listOf("contacts", "contact", "address book", "people"),
        "写真" to listOf("photos", "photo", "gallery", "images"),
        "カメラ" to listOf("camera", "cam"),
        "カレンダー" to listOf("calendar", "schedule"),
        "地図" to listOf("maps", "map", "navigation", "gps"),
        "マップ" to listOf("maps", "map", "navigation", "gps"),
        "天気" to listOf("weather", "forecast"),
        "メモ" to listOf("notes", "note", "memo"),
        "録音" to listOf("recorder", "voice recorder", "audio"),
        "ボイスレコーダー" to listOf("recorder", "voice recorder", "voice"),
        "ブラウザ" to listOf("browser", "internet", "web"),
        "ファイル" to listOf("files", "file manager", "file"),
        "メッセージ" to listOf("messages", "message", "sms", "chat"),
        "メール" to listOf("mail", "email", "gmail"),
        "音楽" to listOf("music", "player", "audio"),
        "乗換案内" to listOf("transit", "transfer", "train"),
        "乗り換え" to listOf("transit", "transfer", "train"),
        "ニュース" to listOf("news"),
        "読書" to listOf("books", "reading", "ebook"),
        "辞書" to listOf("dictionary"),
        "ゲーム" to listOf("games", "game"),
        "ストア" to listOf("store", "market", "shop")
    )
}
